_BASE_: "../Base-BAText.yaml"
# MODEL:
#   BATEXT:
#     POOLER_RESOLUTION: (8,128)
#     NUM_CHARS: 100
#   FCOS:
#     INFERENCE_TH_TEST: 0.6
DATASETS:
  TRAIN: ("vintext_train",)
  TEST: ("vintext_val",)
# INPUT:
#   MIN_SIZE_TEST: 800
#   MAX_SIZE_TEST: 1024
